version: '3.8'

services:
  mybackend:
    build: .
    ports:
      - "5162:5162"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5162
      - ConnectionStrings__MySql=server=mysql-ezbuildvndb.alwaysdata.net;port=3306;database=ezbuildvndb_mysql;user=431603;password=toiyeufpt;SslMode=None
    restart: unless-stopped

  # Optional: Local MySQL (nếu muốn dùng local DB)
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: ezbuild_db
  #     MYSQL_USER: ezbuild_user
  #     MYSQL_PASSWORD: ezbuild_pass
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
